spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Comp
    username: user1
    password: 123456
  mail:
    host: smtp.qq.com
    username: zhouhux@qq.com
    password: zwqhmxwcolyycach
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  redis:
    host: localhost
    port: 6379
    password: 123456

mybatis:
  type-aliases-package: com.example.demo.entity
